# Generated by Django 4.1.3 on 2022-12-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
        ),
        migrations.CreateModel(
            name='BalansCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Shino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(verbose_name='В Наличии')),
            ],
        ),
        migrations.CreateModel(
            name='ShinoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Photo', verbose_name='Фотографии')),
                ('title', models.CharField(max_length=100, verbose_name='Название Товара')),
                ('availiability', models.BooleanField(verbose_name='В Наличии')),
                ('category', models.ManyToManyField(to='api_view.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
