# Generated by Django 4.1.3 on 2022-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='BoxesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='CamberToe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='CamberToeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='CarLifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='CarLiftsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='ConsumablesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='GarageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Gasoline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='GasolineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Jacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='JacksCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Shino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='ShinoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='SparesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='Stands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
                ('availiability', models.BooleanField(null=True, verbose_name='В Наличии')),
            ],
            options={
                'verbose_name': 'Оборудование Шиномонтажа',
                'verbose_name_plural': 'Оборудование Шиномонтажа',
            },
        ),
        migrations.CreateModel(
            name='StandsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='Photo_Category', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Категории Шиномонтажа',
                'verbose_name_plural': 'Категории Шиномонтажа',
            },
        ),
    ]
