# Generated by Django 4.1.3 on 2022-12-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxes',
            options={'verbose_name': 'ящики с инструментами', 'verbose_name_plural': 'ящики с инструментами'},
        ),
        migrations.AlterModelOptions(
            name='boxescategory',
            options={'verbose_name': 'Категории ящики с инструментами', 'verbose_name_plural': 'Категории ящики с инструментами'},
        ),
        migrations.AlterModelOptions(
            name='cambertoe',
            options={'verbose_name': 'Оборудование для развала схождение', 'verbose_name_plural': 'Оборудование для развала схождение'},
        ),
        migrations.AlterModelOptions(
            name='cambertoecategory',
            options={'verbose_name': 'Категории аппараты для развала схождение', 'verbose_name_plural': 'Категории аппараты для развала схождение'},
        ),
        migrations.AlterModelOptions(
            name='carlifts',
            options={'verbose_name': 'Оборудование автомобильные подьемники', 'verbose_name_plural': 'Оборудование автомобильные подьемники'},
        ),
        migrations.AlterModelOptions(
            name='carliftscategory',
            options={'verbose_name': 'Категории автомобильные подьемники', 'verbose_name_plural': 'Категории автомобильные подьемники'},
        ),
        migrations.AlterModelOptions(
            name='consumables',
            options={'verbose_name': 'расходные материалы', 'verbose_name_plural': 'расходные материалы'},
        ),
        migrations.AlterModelOptions(
            name='consumablescategory',
            options={'verbose_name': 'Категории расходные материалы', 'verbose_name_plural': 'Категории расходные материалы'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'гаражные оборудование ', 'verbose_name_plural': 'гаражные оборудование '},
        ),
        migrations.AlterModelOptions(
            name='garagecategory',
            options={'verbose_name': 'Категории гаражные оборудование ', 'verbose_name_plural': 'Категории гаражные оборудование '},
        ),
        migrations.AlterModelOptions(
            name='gasoline',
            options={'verbose_name': 'Оборудование проверка бензонососов', 'verbose_name_plural': 'Оборудование проверка бензонососов'},
        ),
        migrations.AlterModelOptions(
            name='gasolinecategory',
            options={'verbose_name': 'Категории проверка бензонососов', 'verbose_name_plural': 'Категории проверка бензонососов'},
        ),
        migrations.AlterModelOptions(
            name='jacks',
            options={'verbose_name': 'Домкраты', 'verbose_name_plural': 'Домкраты'},
        ),
        migrations.AlterModelOptions(
            name='jackscategory',
            options={'verbose_name': 'Категории Домкратов', 'verbose_name_plural': 'Категории Домкратов'},
        ),
        migrations.AlterModelOptions(
            name='spares',
            options={'verbose_name': 'запчасти к оборудованию', 'verbose_name_plural': 'запчасти к оборудованию'},
        ),
        migrations.AlterModelOptions(
            name='sparescategory',
            options={'verbose_name': 'Категории запчасти к оборудованию', 'verbose_name_plural': 'Категории запчасти к оборудованию'},
        ),
        migrations.AlterModelOptions(
            name='stands',
            options={'verbose_name': 'стенды', 'verbose_name_plural': 'стенды'},
        ),
        migrations.AlterModelOptions(
            name='standscategory',
            options={'verbose_name': 'Категории стенды', 'verbose_name_plural': 'Категории стенды'},
        ),
    ]
