# Generated by Django 4.1.3 on 2022-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shino',
            name='availiability',
            field=models.BooleanField(null=True, verbose_name='В Наличии'),
        ),
    ]
